

============================== 2023-12-03 07:44:45.698626 | 5981a480-a861-4b41-a7f1-46c1a0e0571f ==============================
[0m07:44:45.698626 [info ] [MainThread]: Running with dbt=1.4.9
[0m07:44:45.703690 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': 'C:\\Users\\soory\\.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'project_name': 'dbt_projects', 'skip_profile_setup': False, 'which': 'init', 'indirect_selection': 'eager'}
[0m07:44:45.703690 [debug] [MainThread]: Tracking: tracking
[0m07:44:45.718014 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F257BF1360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F257BF2230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F257BF1930>]}
[0m07:44:45.720008 [debug] [MainThread]: Starter project path: C:\Users\soory\myenv\lib\site-packages\dbt\include\starter_project
[0m07:44:52.089746 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F257BF1AE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F257BF0160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F257BF09A0>]}
[0m07:44:52.090744 [debug] [MainThread]: Flushing usage events
[0m07:44:53.052474 [error] [MainThread]: Encountered an error:

[0m07:44:53.061422 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\soory\myenv\lib\site-packages\dbt\main.py", line 136, in main
    results, succeeded = handle_and_check(args)
  File "C:\Users\soory\myenv\lib\site-packages\dbt\main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
  File "C:\Users\soory\myenv\lib\site-packages\dbt\main.py", line 253, in run_from_args
    results = task.run()
  File "C:\Users\soory\myenv\lib\site-packages\dbt\task\init.py", line 304, in run
    adapter = self.ask_for_adapter_choice()
  File "C:\Users\soory\myenv\lib\site-packages\dbt\task\init.py", line 230, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "C:\Users\soory\myenv\lib\site-packages\click\termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "C:\Users\soory\myenv\lib\site-packages\click\termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m03:51:07.880662 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000263474BE290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002634A68E350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002634A68E110>]}


============================== 03:51:07.887587 | 2a2f0d8f-175d-40c4-9686-b2aa52923f99 ==============================
[0m03:51:07.887587 [info ] [MainThread]: Running with dbt=1.7.8
[0m03:51:07.888587 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\soory\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init dbt_projects', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:51:07.890622 [debug] [MainThread]: Starter project path: C:\Users\soory\myenv\lib\site-packages\dbt\include\starter_project
[0m03:51:07.944373 [info ] [MainThread]: 
Your new dbt project "dbt_projects" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m03:51:07.946858 [info ] [MainThread]: Setting up your profile.
[0m03:53:23.953774 [info ] [MainThread]: Profile dbt_projects written to C:\Users\soory\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m03:53:23.957221 [debug] [MainThread]: Command `dbt init` succeeded at 03:53:23.956373 after 136.10 seconds
[0m03:53:23.958249 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000263474BE290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002634A68F100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002634A68E3E0>]}
[0m03:53:23.958754 [debug] [MainThread]: Flushing usage events
[0m03:54:48.526335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178EB1FBEE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178EE3FDCC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178EE3FE320>]}


============================== 03:54:48.531973 | 0792f55b-efe5-4b68-83e6-8614329d1c4d ==============================
[0m03:54:48.531973 [info ] [MainThread]: Running with dbt=1.7.8
[0m03:54:48.531973 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\soory\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m03:54:48.533482 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\001_Data\data_projects\data_projects\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:54:48.536869 [debug] [MainThread]: Command `dbt run` failed at 03:54:48.535830 after 0.08 seconds
[0m03:54:48.536869 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178EB1FBEE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178EE3FE020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178EE3FEDD0>]}
[0m03:54:48.537867 [debug] [MainThread]: Flushing usage events
[0m16:36:11.883518 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017CA1B5F370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017CA4DDB8B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017CA4DDB6A0>]}


============================== 16:36:11.899211 | c468d2b4-4fbe-4c3c-8cd1-6e81c2c9b28c ==============================
[0m16:36:11.899211 [info ] [MainThread]: Running with dbt=1.7.8
[0m16:36:11.899211 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\soory\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:36:11.899211 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\001_Data\data_projects\data_projects\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:36:11.899211 [debug] [MainThread]: Command `dbt run` failed at 16:36:11.899211 after 0.08 seconds
[0m16:36:11.899211 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017CA1B5F370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017CA4DDB610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017CA4DDB910>]}
[0m16:36:11.899211 [debug] [MainThread]: Flushing usage events
